# Site settings
alert-message: ' and <a href="http://getbootstrap.com" class="alert-link">http://getbootstrap.com</a>.'
category-list: [Widgets, Layouts, Alternate Layouts]
company: PatternFly
navbar-pf-alt-navbar-brand-icon: true
title: PatternFly
title-product: 'PatternFly Enterprise Application'
url-css-additions: '../dist/css/patternfly-additions.min.css'
url-css-extra: 'tests.css'
url-css-main: '../dist/css/patternfly.min.css'
url-img: 'img/'
url-js: '../dist/js/patternfly.min.js'